spring:
  mail:
    host: smtp.qq.com
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    username: 616164124@qq.com
    password: xanlkaeqeckobefh
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        acknowledge-mode: manual  #手动
  elasticsearch:
    rest:
      uris: localhost
